export const REQUEST_CARS = 'REQUEST_CARS';
export const REQUEST_CARS_SUCCESS = 'REQUEST_CARS_SUCCESS';
export const REQUEST_CARS_FAIL = 'REQUEST_CARS_FAIL';
export const REQUEST_AVAILABILITY = 'REQUEST_AVAILABILITY';
export const REQUEST_AVAILABILITY_SUCCESS = 'REQUEST_AVAILABILITY_SUCCESS';
export const REQUEST_AVAILABILITY_FAIL = 'REQUEST_AVAILABILITY_FAIL';
export const SET_SORTING = 'SET_SORTING';

